# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0deb592b39cbb9ce560dad5fa77f3cfa501e9f373bc085177a5940194d69bf99a94427f0af5a83520e2c5f7c0a151b2329b047ef0fd2b04bad8cee1432a36d3e

test:
  secret_key_base: 12caa94fc8d2838c30058c823660f81b8ef01e320ee0b26046661f1a8b81d5cd8279a7580e02bda82d8427f6236f7370a27e93a249937f8de950688ff95020a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
